version: '3'

services:
    postgresql:
        image: postgres:12
        ports:
            - 5432:5432
        env_file:
            - backend/.env
        networks:
            - main

    pgadmin:
        image: dpage/pgadmin4:5.4
        volumes:
            - pg-admin-data:/var/lib/pgadmin
        ports:
            - 5050:5050
        env_file:
            - backend/.env
        depends_on:
            - postgresql
        networks:
            - main

    backend:
        entrypoint: "uvicorn api:app --host 0.0.0.0 --reload"
        ports:
            - 8000:8000
        volumes:
            - ./backend:/backend
        build:
            context: ./backend
            dockerfile: backend.dockerfile
        env_file:
            - ./backend/.env
        networks:
            - main
        depends_on:
            - postgresql
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.http-catchall.rule=PathPrefix(`/api`)
            - traefik.http.routers.http-catchall.entrypoints=secureweb
            - traefik.http.routers.http-catchall.tls.certresolver=letsEncrypt
            - traefik.http.routers.http-catchall.middlewares=clear_prefix
            - traefik.http.middlewares.clear_prefix.stripprefix.prefixes=/api,/dashboard
            - traefik.http.middlewares.clear_prefix.stripprefix.forceSlash=true
            - traefik.http.services.backend.loadbalancer.server.port=8000

    preinsert_data:
        volumes:
            - ./backend:/backend
        entrypoint: "python3 preinsert_db.py"
        build:
            context: ./backend
            dockerfile: backend.dockerfile
        env_file:
            - ./backend/.env
        networks:
            - main
        depends_on:
            - postgresql
            - backend

    traefik:
        image: traefik:v2.3
        ports:
            - 80:80
            - 443:443
            # traefik dashboard
#            - 8080:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./traefik/traefik.yml:/traefik.yml:ro
            - ./traefik/dashboard.yml:/traefik/dashboard.yml:ro
            - ./traefik/acme.json:/traefik/acme.json
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - main


networks:
    main:
        
volumes:
  pg-admin-data:

