"""Init

Revision ID: 78076b613d57
Revises: 
Create Date: 2022-04-08 20:01:54.782988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78076b613d57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttonevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_long_click', sa.Boolean(), nullable=True),
    sa.Column('pushed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buttonevent_id'), 'buttonevent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buttonevent_id'), table_name='buttonevent')
    op.drop_table('buttonevent')
    # ### end Alembic commands ###
